name: Deploy to MySQL

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy SQL Scripts to MySQL
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.MYSQL_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          # Create the tracking table if it doesn't exist
          mysql -h ${{ secrets.MYSQL_HOST }} -u ${{ secrets.MYSQL_USER }} -p${{ secrets.MYSQL_PASSWORD }} ${{ secrets.MYSQL_DATABASE }} <<EOF
          CREATE TABLE IF NOT EXISTS executed_scripts (
            script_name VARCHAR(255) PRIMARY KEY,
            executed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
          );
          EOF

          # Execute only new DML scripts
          for sql_file in $(find DML -name '*.sql'); do
            script_name=$(basename $sql_file)
            if ! mysql -h ${{ secrets.MYSQL_HOST }} -u ${{ secrets.MYSQL_USER }} -p${{ secrets.MYSQL_PASSWORD }} ${{ secrets.MYSQL_DATABASE }} -e "SELECT 1 FROM executed_scripts WHERE script_name='$script_name'" | grep 1; then
              mysql -h ${{ secrets.MYSQL_HOST }} -u ${{ secrets.MYSQL_USER }} -p${{ secrets.MYSQL_PASSWORD }} ${{ secrets.MYSQL_DATABASE }} < $sql_file;
              mysql -h ${{ secrets.MYSQL_HOST }} -u ${{ secrets.MYSQL_USER }} -p${{ secrets.MYSQL_PASSWORD }} ${{ secrets.MYSQL_DATABASE }} -e "INSERT INTO executed_scripts (script_name) VALUES ('$script_name')";
            fi
          done
